pcm.!default {
    type pipewire
    playback_node "-1"
    capture_node  "-1"
    hint {
        show on
        description "PipeWire Media Server"
    }
}

ctl.!default {
    type pipewire
}

ctl.soundcard {
  type equal;
}

pcm.plugequal {
  type equal;
  slave.pcm "plughw:0,0";
}

pcm.soundcard {
  type plug;
  slave.pcm plugequal;
}

pcm.hardware {
    type hw
    card 0
    device 0
}

pcm.pipewire {
    type pipewire
    playback_node "-1"
    capture_node  "-1"
    hint {
        show on
        description "PipeWire Media Server"
    }
}

ctl.pipewire {
    type pipewire
}

