services:
  pipewire:
    extra_hosts:
      - pipewire:127.0.0.1
    network_mode: host
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    environment:
      - TZ=Europe/London
      - MEMCACHE=true
    ports:
      - 8000:8000
      - 1780:1780
    container_name: pipewire
    hostname: pipewire
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true
    cap_add:
      - SYS_NICE
      - CAP_IPC_LOCK
      - CAP_NET_ADMIN
      - SYS_RAWIO
